### ISSUE TITLE
workflow: Create a README that's actually useful

### ISSUE THREAD

**Issue by trentgillis** [trentgillis/prime-condies#51]
- We still have the default README. Let's change that shall we
- Should include: dev env setup instructions, high level info about the project

**Comment by Philip-A-R** [comment]
@trentgillis  I can give this a spin as well. You'll probably have to go through and edit, but I'll at least get a draft out there.

**Comment by Philip-A-R** [comment]
**PrimeCondies**

PrimeCondies is a web app built for climbers to see the weather conditions of their favorite outdoor boulders.

We opted for NextJS because it allows us to define lightweight api routes and gives us some opinionation. It also acts as a server to host the app.
**Getting Started**
First, run the development server:
```
pnpm install
pnpm run dev
```

Open http://localhost:3000/ with your browser to see the result.

**Usage**
**Contributing**
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.
Please make sure to update tests as appropriate.
**License:**
MIT

**Comment by Philip-A-R** [comment]
Ok, so this is obviously pretty lightweight, but I think that it covers where we are at right now right? @trentgillis or do we want it to be super thorough? Also, do we need to include things like setting up docker?

**Comment by trentgillis** [comment]
@Philip-A-R I would definitely mention that a running instance of redis and mongo is require to run the application and then have instructions around how to run those via docker with our compose file

**Comment by Philip-A-R** [comment]
@trentgillis Ok, I have re-written this a couple of times but feel like I don't acutally understand this part of this well enough to write the ReadMe portion. :/ I've read through the docks. maybe you could run me through how we set it up again from square one at some point.
